version: '3.8'
services:
  app:
    build: .
    ports:
      - '4001:4000'
    depends_on:
      db:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=api_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=test1231231231239898
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api_db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  liquibase:
    image: liquibase/liquibase:latest
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./liquibase/changelog:/liquibase/changelog
    entrypoint: ["liquibase"]
    command:
      [
        "--changeLogFile=changelog/db.changelog-master.xml",
        "--url=jdbc:postgresql://db:5432/api_db",
        "--username=postgres",
        "--password=postgres",
        "update"
      ]

volumes:
  db_data:
